version: "3"
services:
  php:
    container_name: ${PROJECT_NAME}_web
    build: .
    ports:
      - ${APACHE_HOST_HTTP_PORT}:80
      - ${APACHE_HOST_HTTPS_PORT}:443
    volumes:
      - ${APP_FOLDER}/${PROJECT_NAME}:/var/www/html
    networks:
      - app-network
  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge
